platform :ios, '9.0'
target 'ACands' do
# Required by RNFirebase
pod 'Firebase/Core', '~> 5.11.0'
pod 'Firebase/Auth', '~> 5.11.0'
pod 'Firebase/Messaging', '~> 5.11.0'
pod 'Firebase/Database', '~> 5.11.0'
pod 'Firebase/Storage', '~> 5.11.0'
pod 'GoogleAppMeasurement', '5.3.0'
end